### ISSUE TITLE
Quest detection fails - "Discount" in the Thaumcraft chapter.

### ISSUE THREAD

**Issue by BluCalculator** [MyM-ModpackTeam/hypovolemia#353] opened 2016-08-14 03:28 UTC
It doesn't detect the sanguine set.
![2016-08-14_12 57 37](https://cloud.githubusercontent.com/assets/3198310/17646991/b8845514-621e-11e6-9331-ccd23760d26b.png)

Sanguine Helmet (ID 5234)
Sanguine Robes (ID 5235)
Sanguine Leggings (ID 5236)
Sanguine Boots (ID 5237)

**Comment by YourMCGeek** [comment] 2016-10-23 20:35
They detected for me?

**Comment by YourMCGeek** [comment] 2016-10-24 00:32
Done.

**Comment by johnfg12** [comment] 2016-10-24 23:02
since mcgeek says the issue is fixed il close this

**Closed by johnfg12** 2016-10-24 23:02 UTC
Labels: in progress, quest
