### ISSUE TITLE
MFR factory machine blocks missing recipe

### ISSUE THREAD

**Issue by Alifalafel** [MyM-ModpackTeam/hypovolemia#373] opened 2016-09-10 19:03 UTC
The factory machine blocks from Minefactory Reloaded are uncraftable, as far as I can tell. The old recipe (plastic sheets top and bottom rows, with iron gears in the center) doesn't make them, and no recipe shows up in NEI at all after the most recent update.

**Comment by kindlich** [comment] 2016-09-10 19:27
First: The Recipe was changed to this:
plastic Sheet, plastic Sheet, plastic Sheet
iron gear, iron gear, iron gear
plastic Sheet, plastic Sheet, plastic Sheet
Could you test if that works on the server?

2nd Did you try to join the server, disconnect and then rejoin?
There is a client-server synchronisation Error that I just cannot get behind as of now...

**Comment by kindlich** [comment] 2016-09-10 20:06
Ok, just checked, the recipe works fine, just doesn't show up in NEI, so it's a dupe of 
#372

**Closed by kindlich** 2016-09-10 20:06 UTC
