### ISSUE TITLE
Craked bones issue

### ISSUE THREAD

**Issue by LaytoMax35** [MyM-ModpackTeam/hypovolemia#155] opened 2016-01-01 02:06 UTC
I think this is a bug i look up in nei for craked bones and it say the recipe is 4 bones and 1 gunpowder in the alchemic chemistry set but i did that and nothing happened (i had the blood orb obvious) and it say 0% (blood orb is charged and i'm not the only one that happens this on)

**Comment by lavalemming** [comment] 2016-01-12 04:45
I tested an idea and I might be able to explain what happened to your attempt.  Look at the id number of the bones you are using.  I found 352 and 352:1; I'm assuming one is from skeleton kills and one is mined from bone spikes in the world.  If I used id # 352 the cracked bones worked for me perfect, with 352:1 id number bones it would not work.

**Comment by Bennyboy1695** [comment] 2016-01-12 07:36
This is a known issue, caithleen had made a ore dictionary value for it but it doesn't seem to work properly. The issue is that the bones get from breaking the bones in the over world drop bones with a :1 data value, whereas normal bones gotten from skeletons or other ways give the correct bone which is without the :1 . This is caused by the mod that is making the bones in the overworld is unable to drop the correct bone due to a bug, I had made a fix of this for caithleen but I don't believe it has been implemented yet :P

**Comment by Slind14** [comment] 2016-01-12 11:48
I believe this is fixed in the latest version which is not yet deployed.

**Comment by pizzaluc** [comment] 2016-01-30 18:22
Can confirm that this is now working on the version currently on the server

**Comment by Slind14** [comment] 2016-01-30 20:17
thanks

**Closed by Slind14** 2016-01-30 20:17 UTC
