### ISSUE TITLE
Can't Create a world

### ISSUE THREAD

**Issue by LifeHckr** [MyM-ModpackTeam/hypovolemia#150] opened 2015-12-22 22:56 UTC
I just downloaded the pack and when I tried creating a world it brought me back to the main menu and I can't create a world.

**Comment by drz2k** [comment] 2015-12-23 11:04
Retry to enter that world, slower machines struggle with worldgen but usually can login to the world after several tries.

**Comment by lw03** [comment] 2015-12-27 04:09
i am also having this issue when i try to start a world it just returns me to the main menue

**Comment by LifeHckr** [comment] 2015-12-29 02:12
I can't create a world in general it doesnt show in world list.

**Comment by drz2k** [comment] 2015-12-30 08:22
Logs?

**Comment by lw03** [comment] 2015-12-30 09:24
[latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74717/latest.txt)
[fml-junk-earlystartup.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74718/fml-junk-earlystartup.txt)
[fml-client-latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74719/fml-client-latest.txt)

thats all i have i tryed pastebin and it wouldnt work so i hope this does

**Comment by drz2k** [comment] 2015-12-30 10:33
[09:16:43] [Server thread/ERROR] [FML/]: Caught exception from BiomeTweaker
java.io.IOException: Access is denied

Try to launch as admin ...

**Comment by lw03** [comment] 2015-12-30 10:38
i have allready doesnt help

**Comment by drz2k** [comment] 2015-12-30 11:48
Well try different launcher, different location. The problem is that your mc isnt allowed to create specific files.

**Comment by lw03** [comment] 2015-12-30 11:52
i should have stated that i have been able to play it before so i dont see how that can be the case

**Comment by drz2k** [comment] 2015-12-30 13:05
Try to delete the stuff in /config/biometweaker/output...

**Comment by lw03** [comment] 2015-12-30 13:28
nope that doesnt help

**Comment by drz2k** [comment] 2015-12-30 22:24
Well, the error message clearly points to a problem writing to your file system. I gave advices on that, if you dont want to test them, i dont see how i can be of any more help.

**Comment by lw03** [comment] 2015-12-31 02:56
i have just done everything you said... you saying i am not willing to try is fucking rude fuck your pack ill play something else prick

**Comment by drz2k** [comment] 2015-12-31 12:00
Closing it, since its not related to the pack and the creator started insulting ;)

**Closed by drz2k** 2015-12-31 12:00 UTC

**Comment by lw03** [comment] 2015-12-31 12:03
1. im not the creator
2. you insulted me by saying i wasnt testing whatever you said when indeed i did.
