### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#186] opened 2016-06-14 15:45 UTC
Is there a way to change the metadata on the bones? Most recipes don't recognize the versions you find out in the wasteland with the :1 on the end, and the normal ones skeletons drop stack with them and change into them. This has prevented me from doing stuff like, for example, using witchery wood ash to multiply bonemeal.

**Comment by Slind14** [comment] 2016-06-14 15:48
this is the cause:
https://github.com/MyM-ModpackTeam/hypovolemia/commit/54f53aa1c815b5744885a92519129cc7a26d5c48#diff-0d12b5b984e667bf32a940ded7acb8f8L2
But there should no longer be any with `:1`

**Comment by johnfg12** [comment] 2016-06-14 16:03
ok il close this then :)

**Closed by johnfg12** 2016-06-14 16:03 UTC

**Comment by SirStudMuffin** [comment] 2016-06-14 19:23
Thanks was just moving issues from FTB to GitHub so
