### ISSUE TITLE
High tech power sources?

### ISSUE THREAD

**Issue by Biteboy5** [MyM-ModpackTeam/hypovolemia#154] opened 2015-12-28 19:16 UTC
I was wondering if it is possible for us to have like the Mekanism Reactor maybe increase the costs to create or something because spamming blood dynamos and mana/thaum ones really takes up a lot of room and barely makes any power

**Comment by chuggafan** [comment] 2015-12-28 22:41
Already suggested, duplicate

**Comment by Bennyboy1695** [comment] 2015-12-28 22:50
Duplicate of #85

**Closed** 2015-12-30 08:20 UTC
Labels: duplicate
