### ISSUE TITLE
World Creation

### ISSUE THREAD

**Issue by EvadeCarnage** [MyM-ModpackTeam/hypovolemia#172] opened 2016-03-30 21:05 UTC
when ever i go and create a world its starts to load for a few seconds and then suddenly goes back to the title screen without saying anything about errors and it leaves no sign that a world was created.

**Comment by chuggafan** [comment] 2016-03-30 23:06
duplicate, it SOMETIMES works though

**Comment by EvadeCarnage** [comment] 2016-03-31 08:06
nope still doesn't work

**Comment by chuggafan** [comment] 2016-03-31 11:49
I have done it before, it's rare, idk how to get it to work

**Comment by kindlich** [comment] 2016-03-31 12:23
have you tried to delete your instance of hypo and re-download it?

**Comment by midnight4sale** [comment] 2016-03-31 13:05
Ok, so the problem with the pack is BiomeTweaker.  After searching for about an hour or so and testing with and without BiomeTweaker that is the conclusion I reached.  Something with the mod kills the world gen before it can finish.  A world launches without it but without it, that defeats the purpose of the game.  I have tried downloading an older version of BiomeTweaker, even using an earlier version of the pack, but nothing has worked.  After saying all of this, a reboot will not fix it and neither will a re-download/install of the pack.  It has something to do with how Java is starting the pack.  I've tried setting everything to run as admin in Java but again, that didn't help.  I have tried the FTB as well as the Curse Launchers.  Below is the code.

[BiomeTweaker Bug.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/197664/BiomeTweaker.Bug.txt)

**Comment by chuggafan** [comment] 2016-03-31 13:10
I've made worlds before, in version .19, in version .4, so it SOMETIMES works, i don't know why it doesn't though, sometimes it does, sometimes it odesn't

**Comment by midnight4sale** [comment] 2016-03-31 13:13
Well it would seem as of late, the pack won't load and that is the problem above.  Granted it may work some times but these topics keep getting closed with no conclusion on what to do.  I just wanted to put out what I had discovered and see what could be done since I'm not good enough with code to fix any of this.

**Comment by chuggafan** [comment] 2016-03-31 13:15
Yhea, the access is denied thing is something we've tried to figure out for awhile now, it's really weird, no clue why it happens

**Comment by midnight4sale** [comment] 2016-03-31 13:18
Ok well I just wanted to post what I had discovered.  Maybe there's a way around it but it just hasn't been found yet.  But it would seem this seems to be the problem based on what other threads keep describing about world gen.  It seems like an awesome pack, just can't seem to play it at the moment :/

**Comment by kindlich** [comment] 2016-03-31 14:10
did you try to reset the file attributes of your MC folder?

I mean, if it sais it doesnt have access to some files maybe it got some kind of writing protection...

Just open the your folder's settings and see if there's a cross or square at the "read-only" option (it could have an other name, my OS is in an other language)

just try and see whether this allows java/biome tweaker to write to the files?

**Comment by midnight4sale** [comment] 2016-03-31 14:24
I tried it but the issue persists with the same error.  Again, the problem appears to be BiomeTweaker and how it is interacting with Java.  So my guess is it's something only the creator of the mod could fix unless the pack owner somehow knows how.

**Comment by DougJP2** [comment] 2016-04-30 00:37
so I am assuming that this issue has not been fixed?  Its been a month according to this report.

**Comment by Arcanuo** [comment] 2016-04-30 01:09
I can't really do anything here, if I could get some sort of log, that'd be a different story, but the new world gen in the next update might fix this.

**Comment by DougJP2** [comment] 2016-04-30 01:18
http://paste.feed-the-beast.com/view/6ac85644

**Comment by Arcanuo** [comment] 2016-04-30 01:58
Thanks.

Not sure how much help that will be in the run, but will look at it when I wake up.

**Comment by Sir-Will** [comment] 2016-04-30 07:09
`Caused by: java.io.IOException: Access is denied`
Issue is on your side. Something prevents BiomeTweaker from creating files.

**Comment by DougJP2** [comment] 2016-05-02 04:42
How can I fix that?

**Comment by johnfg12** [comment] 2016-05-02 16:15
i would guess go into the java control pannel and decrease security level?

**Comment by johnfg12** [comment] 2016-06-13 09:58
not modpack issue :)

**Closed** 2016-06-13 09:58 UTC
Labels: invalid
