### ISSUE TITLE
New World

### ISSUE THREAD

**Issue by CookieMonsterV21** [MyM-ModpackTeam/hypovolemia#165] opened 2016-03-21 23:57 UTC
I can't seem to make a new world and when i launch Hypovolemia it says "Error extracting native libraries"

**Comment by chuggafan** [comment] 2016-03-24 11:58
If the modpack launches it's fine, also: are you logging onto the server before doing this? this seems to actually allow me to make a new world for some reason, it's REALLY weird

**Comment by johnfg12** [comment] 2016-06-13 09:52
can we have logs ect plz il take a look in a bit

**Comment by Slind14** [comment] 2016-06-13 10:15
The world creation issues are caused by biome tweaker, the repo has the latest "improved" version but the launchers don't.

**Comment by johnfg12** [comment] 2016-06-13 11:38
ok so this is sorted on the latest version?

**Comment by Slind14** [comment] 2016-06-13 11:46
should be, if not, there is not much we can do from our side.

**Comment by johnfg12** [comment] 2016-06-13 12:15
ok then il close this then :)

**Closed by johnfg12** 2016-06-13 12:15 UTC
Labels: bug
