### ISSUE TITLE
World drops before it finishes loading

### ISSUE THREAD

**Issue by ZelmodthePsi** [MyM-ModpackTeam/hypovolemia#170] opened 2016-03-29 15:57 UTC
I'm honestly not sure what I did wrong this time.  It was working fine last night, I shut down the world but left the main screen up (so that I could skip the long loading process through FTB) and put the comp to sleep.  When I got up today and went to boot it up, it crashed when I selected the world to load.   I hope this is the right chunk of the crash report to bring here.  Running single player on a high spec computer.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/29/16 10:51 AM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -19
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:28)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75)
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548)
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878)
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

This is isn't the first world this has happened to, last time I just did what I could to pick up the pieces and reset a new world but I reeeeally don't want to do that again if I can fix it.  I don't think I made any strenuous automatons or connections this time round though.  I hope that we can reach a conclusion, good or bad.

**Comment by chuggafan** [comment] 2016-03-29 20:35
Try get back into the world, might work now that you got a nice little restart for your minecraft launcher (It's probably because of the garbage collector, maybe...) so closing java and reopening *should* fix

**Comment by ZelmodthePsi** [comment] 2016-03-29 21:36
Same result with the same error listed in the report.

**Comment by chuggafan** [comment] 2016-03-29 22:23
have you tried rebooting your computer? could be a legit "reboot and you're fine" case, as it's crashing at the minecraft server trying to parse data to SOMETHING

**Comment by ZelmodthePsi** [comment] 2016-03-30 03:51
Same result still...darn

**Comment by GGothicRide** [comment] 2016-06-14 16:43
what are the computer specs and the java version you are running as well as the operating system, this could help determine the cause of this

**Comment by Slind14** [comment] 2016-06-14 19:26
Looks like a corrupted world, most likely caused by software or hardware issues unrelated to the pack. Something interrupting the save.

**Comment by johnfg12** [comment] 2016-06-26 09:00
not pack related

**Closed by johnfg12** 2016-06-26 09:00 UTC
Labels: question
